// @ts-nocheck
import crypto from "node:crypto";
import path from "node:path";
import Fastify from "fastify";
import cors from "@fastify/cors";
import helmet from "@fastify/helmet";
import compress from "@fastify/compress";
import cookie from "@fastify/cookie";
import fastifyStatic from "@fastify/static";
import rateLimit from "@fastify/rate-limit";
import mongoose from "mongoose";
import { env } from "./config/env.js";
import { logger } from "./lib/logger/index.js";
import { metricsRegistry } from "./lib/monitoring/index.js";
import { isValkeyConnected } from "./lib/valkey.js";
import { errorHandler } from "./middleware/error.js";
const app = Fastify({ logger: false, trustProxy: true as any, bodyLimit: 10 * 1024 * 1024 });
app.addHook("onRequest", async (req, _reply) => { if (req.url.includes("//")) (req as any).url = req.url.replace(/\/+/g, "/"); });
const isProd = env.NODE_ENV === "production";
await app.register(helmet, { contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'", "'strict-dynamic'", ...(isProd ? [] : ["'unsafe-inline'", "'unsafe-eval'"])], styleSrc: ["'self'", "https://fonts.googleapis.com", ...(isProd ? [] : ["'unsafe-inline'"])], fontSrc: ["'self'", "https://fonts.gstatic.com", "data:"], imgSrc: ["'self'", "data:", "blob:", env.APP_URL, env.R2_PUBLIC_URL].filter(Boolean) as string[], connectSrc: ["'self'", env.APP_URL, env.BASE_URL_WS, env.R2_ENDPOINT].filter(Boolean) as string[], objectSrc: ["'none'"], mediaSrc: ["'self'", "blob:", "data:", env.R2_PUBLIC_URL].filter(Boolean) as string[], frameAncestors: ["'self'", env.R2_PUBLIC_URL].filter(Boolean) as string[], frameSrc: ["'self'", env.R2_PUBLIC_URL].filter(Boolean) as string[], baseUri: ["'self'"], formAction: ["'self'", env.APP_URL].filter(Boolean) as string[], manifestSrc: ["'self'"], workerSrc: ["'self'", "blob:"], ...(isProd ? { upgradeInsecureRequests: [] } : {}), } }, crossOriginEmbedderPolicy: false, crossOriginOpenerPolicy: false, crossOriginResourcePolicy: false });
await app.register(cors, { origin: env.CORS_ORIGIN, credentials: true });
await app.register(compress, { threshold: 1024 });
await app.register(cookie);
await app.register(rateLimit, { global: false, max: 600, timeWindow: "15 minutes" });
await app.register(fastifyStatic, { root: path.resolve("data", "uploads"), prefix: "/uploads/", decorateReply: false, maxAge: 86400000 });
await app.register(fastifyStatic, { root: path.resolve("public", "banners"), prefix: "/banners/", decorateReply: false, maxAge: 86400000 });
app.addHook("onRequest", async (req, reply) => { if (req.url.startsWith("/api") && req.method === "GET") reply.header("Cache-Control", "private, no-cache, no-store, must-revalidate"); });
app.addHook("onRequest", async (req, reply) => { const id = (req.headers["x-request-id"] as string) || crypto.randomUUID(); (req.headers as any)["x-request-id"] = id; (req as any).startTime = Date.now(); reply.header("X-Request-Id", id); });
app.addHook("onResponse", async (req, reply) => { const duration = Date.now() - ((req as any).startTime || Date.now()); const rid = req.headers["x-request-id"] as string; metricsRegistry.incrementCounter("api_requests_total", { method: req.method, path: req.url, status: String(reply.statusCode) }); metricsRegistry.observeHistogram("api_request_duration_ms", { method: req.method, path: req.url }, duration); if (reply.statusCode >= 500) logger.error({ requestId: rid, method: req.method, path: req.url, status: reply.statusCode, duration }, "Request failed"); });
import authPlugin from "./routes/auth.js";
import tasksPlugin from "./routes/tasks.js";
import sessionsPlugin from "./routes/sessions.js";
import notificationsPlugin from "./routes/notifications.js";
import activityPlugin from "./routes/activity.js";
import dashboardPlugin from "./routes/dashboard.js";
import drawingsPlugin from "./routes/drawings.js";
import usersPlugin from "./routes/users.js";
import organizationsPlugin from "./routes/organizations.js";
import filesEnhancedPlugin from "./routes/files-enhanced.js";
import filesTusPlugin from "./routes/files-tus.js";
import foldersPlugin from "./routes/folders.js";
import sharesPlugin from "./routes/shares.js";
import searchPlugin from "./routes/search.js";
import userPlugin from "./routes/user.js";
import clientsPlugin from "./routes/clients.js";
import clientAuthPlugin from "./routes/client-auth.js";
import projectsPlugin from "./routes/projects.js";
import teamsPlugin from "./routes/teams.js";
import timeEntriesPlugin from "./routes/time-entries.js";
import adminPlugin from "./routes/admin.js";
import settingsPlugin from "./routes/settings.js";
import fileApprovalPlugin from "./routes/file-approval.js";
import chatPlugin from "./routes/chat.js";
import installerPlugin from "./routes/installer.js";
import appointmentsPlugin from "./routes/appointments.js";
import stocksPlugin from "./routes/stocks.js";
import billingPlugin from "./routes/billing.js";
import receiptsPlugin from "./routes/receipts.js";
import fileFavoritesPlugin from "./routes/file-favorites.js";
import clientFoldersPlugin from "./routes/client-folders.js";
import consentPlugin from "./routes/consent.js";
import analyticsPlugin from "./routes/analytics.js";
import bootstrapPlugin from "./routes/bootstrap.js";
import contractorsPlugin from "./routes/contractors.js";
import blogPlugin from "./routes/blog.js";
import schedulerPlugin from "./routes/scheduler.js";
import timesheetPlugin from "./routes/timesheet.js";
import accountsPlugin from "./routes/accounts.js";
import callsPlugin from "./routes/calls.js";
import presencePlugin from "./routes/presence.js";
import adminConsentPlugin from "./routes/admin-consent.js";
import cronRunnerPlugin from "./routes/cron-runner.js";
import dailyTaskPlugin from "./routes/daily-task-email-scheduler.js";
await app.register(authPlugin, { prefix: "/api/auth" });
await app.register(tasksPlugin, { prefix: "/api/tasks" });
await app.register(sessionsPlugin, { prefix: "/api/sessions" });
await app.register(notificationsPlugin, { prefix: "/api/notifications" });
await app.register(activityPlugin, { prefix: "/api/activity" });
await app.register(dashboardPlugin, { prefix: "/api/dashboard" });
await app.register(drawingsPlugin, { prefix: "/api/drawings" });
await app.register(usersPlugin, { prefix: "/api/users" });
await app.register(organizationsPlugin, { prefix: "/api/organizations" });
await app.register(filesEnhancedPlugin, { prefix: "/api/files" });
await app.register(filesTusPlugin, { prefix: "/api/files-tus" });
await app.register(foldersPlugin, { prefix: "/api/folders" });
await app.register(sharesPlugin, { prefix: "/api/shares" });
await app.register(searchPlugin, { prefix: "/api/search" });
await app.register(userPlugin, { prefix: "/api/user" });
await app.register(clientsPlugin, { prefix: "/api/clients" });
await app.register(clientAuthPlugin, { prefix: "/api/client-auth" });
await app.register(projectsPlugin, { prefix: "/api/projects" });
await app.register(teamsPlugin, { prefix: "/api/teams" });
await app.register(timeEntriesPlugin, { prefix: "/api/time-entries" });
await app.register(adminPlugin, { prefix: "/api/admin" });
await app.register(settingsPlugin, { prefix: "/api/settings" });
await app.register(fileApprovalPlugin, { prefix: "/api/file-approval" });
await app.register(chatPlugin, { prefix: "/api/chat" });
await app.register(installerPlugin, { prefix: "/api/installer" });
await app.register(appointmentsPlugin, { prefix: "/api/appointments" });
await app.register(stocksPlugin, { prefix: "/api/stocks" });
await app.register(billingPlugin, { prefix: "/api/billing" });
await app.register(receiptsPlugin, { prefix: "/api/receipts" });
await app.register(fileFavoritesPlugin, { prefix: "/api/file-favorites" });
await app.register(clientFoldersPlugin, { prefix: "/api/client-folders" });
await app.register(consentPlugin, { prefix: "/api/consent" });
await app.register(analyticsPlugin, { prefix: "/api/analytics" });
await app.register(bootstrapPlugin, { prefix: "/api/bootstrap" });
await app.register(contractorsPlugin, { prefix: "/api/contractors" });
await app.register(blogPlugin, { prefix: "/api/blog" });
await app.register(schedulerPlugin, { prefix: "/api/scheduler" });
await app.register(timesheetPlugin, { prefix: "/api/timesheet" });
await app.register(accountsPlugin, { prefix: "/api/accounts" });
await app.register(callsPlugin, { prefix: "/api/calls" });
await app.register(presencePlugin, { prefix: "/api/presence" });
await app.register(adminConsentPlugin, { prefix: "/api/admin" });
await app.register(cronRunnerPlugin, { prefix: "/api/cron" });
await app.register(dailyTaskPlugin, { prefix: "/api/daily-task-email-scheduler" });
app.get("/metrics", async (_req, reply) => { const mem = process.memoryUsage(); metricsRegistry.setGauge("process_memory_heap_used_bytes", {}, mem.heapUsed); metricsRegistry.setGauge("process_memory_heap_total_bytes", {}, mem.heapTotal); metricsRegistry.setGauge("process_memory_rss_bytes", {}, mem.rss); metricsRegistry.setGauge("process_uptime_seconds", {}, process.uptime()); reply.header("Content-Type", "text/plain; version=0.0.4").send(metricsRegistry.getPrometheusFormat()); });
app.get("/api/health", async (_req, reply) => { const checks: Record<string, string> = {}; let healthy = true; checks.mongodb = mongoose.connection.readyState === 1 ? "connected" : "disconnected"; if (mongoose.connection.readyState !== 1) healthy = false; try { checks.valkey = isValkeyConnected() ? "connected" : "disconnected"; checks.redis = checks.valkey; } catch { checks.valkey = "error"; } const mem = process.memoryUsage(); reply.send({ success: true, status: healthy ? "ok" : "degraded", version: process.env.npm_package_version || "1.0.0", checks, metrics: { memory: { heapUsed: Math.round(mem.heapUsed/1024/1024), heapTotal: Math.round(mem.heapTotal/1024/1024), rss: Math.round(mem.rss/1024/1024) }, uptime: Math.round(process.uptime()) }, timestamp: new Date().toISOString() }); });
app.get("/api/config/public", async (_req, reply) => { reply.send({ maxFileSize: env.MAX_FILE_SIZE, maxFilesPerUpload: env.MAX_FILES_PER_UPLOAD, tusMaxSize: env.TUS_MAX_SIZE, chunkSize: 5*1024*1024, maxConcurrency: 4, directUploadThreshold: 50*1024*1024 }); });
app.setNotFoundHandler((req, reply) => reply.status(404).send({ success: false, error: `Route not found: ${req.method} ${req.url}` }));
app.setErrorHandler(errorHandler as any);
export default app;
