export const collections = {
  users: "users",
  sessions: "sessions",
  organizations: "organizations",
  orgMembers: "org_members",
  teams: "teams",
  teamMembers: "team_members",
  tasks: "tasks",
  notifications: "notifications",
  activityLogs: "activity_logs",
  messages: "messages",
  apiKeys: "api_keys",
  fileAttachments: "file_attachments",
  fileShares: "file_shares",
  timeEntries: "time_entries",
  ssoConfigs: "sso_configs",
  projects: "projects",
} as const;
