export const INDUSTRIES = [
  "Accounting",
  "Accelerators",
  "Advertising",
  "Aerospace",
  "Affiliate Marketing",
  "Agriculture",
  "Agriculture Equipment",
  "Agritech",
  "Animation",
  "Apparel",
  "Architecture",
  "Art & Antiques",
  "Artificial Intelligence (AI)",
  "Asset Management",
  "Astrology",
  "Auction Houses",
  "Auction Services",
  "Auditing",
  "Automotive",
  "Aviation",
  "Bakeries",
  "Banking",
  "Beauty & Cosmetics",
  "Bioenergy",
  "Biotechnology",
  "Blockchain",
  "Branding",
  "Broadcasting",
  "Business Consulting",
  "Business Incubators",
  "Business Intelligence",
  "Cafes",
  "Call Centers",
  "Carbon Management",
  "Catering",
  "Cement",
  "Chambers of Commerce",
  "Chemicals",
  "Childcare",
  "Cleaning Services",
  "ClimateTech",
  "Clinics",
  "Cloud Computing",
  "Cloud Kitchen",
  "Co-working Spaces",
  "Coaching Institutes",
  "Cold Storage",
  "Colleges & Universities",
  "Compliance",
  "Computer Hardware",
  "Conglomerates",
  "Construction",
  "Construction Equipment",
  "Consulting",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cooperative Societies",
  "Corporate Services",
  "Courier Services",
  "CRM Services",
  "Cryptocurrency",
  "Customs Brokerage",
  "Cybersecurity",
  "Data Science",
  "Defense",
  "Defense Technology",
  "Dental Care",
  "DevOps",
  "Diagnostics",
  "Digital Payments",
  "Digital Services",
  "Document Management",
  "Drone Technology",
  "E-commerce",
  "E-learning",
  "EdTech",
  "Education",
  "Elder Care",
  "Electric Vehicles (EV)",
  "Electronics",
  "Email Marketing",
  "Engineering",
  "Entertainment",
  "Environmental Services",
  "ERP Solutions",
  "Event Management",
  "Facility Management",
  "Fashion",
  "Film Production",
  "Finance",
  "Financial Services",
  "FinTech",
  "Fitness & Wellness",
  "FMCG",
  "Food & Beverage",
  "Food Technology (FoodTech)",
  "Footwear",
  "Forestry",
  "Franchising",
  "Freight Forwarding",
  "Funeral Services",
  "Furniture",
  "Gaming",
  "Gift & Stationery",
  "Government",
  "Graphic Design",
  "Green Technology",
  "Handicrafts",
  "HealthTech",
  "Healthcare",
  "Holding Companies",
  "Home Decor",
  "Hospitality",
  "Hospitality Technology",
  "Hospitals",
  "Hotels & Resorts",
  "Household Products",
  "HR Services",
  "Hydropower",
  "Immigration Services",
  "Import & Export",
  "Industrial Automation",
  "Industrial Equipment",
  "Influencer Marketing",
  "Information Technology (IT)",
  "Infrastructure",
  "Inspection Services",
  "Insurance",
  "Interior Design",
  "International Trade",
  "Internet of Things (IoT)",
  "Investment",
  "Jewelry",
  "Knowledge Management",
  "KPO",
  "Laboratory Services",
  "Last-Mile Delivery",
  "Laundry Services",
  "Law Firms",
  "Legal Services",
  "Localization",
  "Logistics",
  "Luxury Goods",
  "Luxury Services",
  "Machine Learning",
  "Management Consulting",
  "Manufacturing",
  "Maritime",
  "Market Research",
  "Marketing",
  "Media",
  "Medical Devices",
  "Medical Equipment",
  "Mental Health",
  "Membership Organizations",
  "Metals",
  "Microfinance",
  "Mining",
  "Mobile App Development",
  "Mobility Services",
  "Music",
  "Nanotechnology",
  "NGO",
  "Non-Profit",
  "Nuclear Energy",
  "Office Supplies",
  "Oil & Gas",
  "Outsourcing (BPO)",
  "Packaging Solutions",
  "Paper",
  "Personal Care",
  "Pest Control",
  "Petrochemicals",
  "Pharmaceuticals",
  "Photography",
  "Plastics",
  "Printing & Packaging",
  "Private Equity",
  "Procurement",
  "Professional Associations",
  "Property Technology (PropTech)",
  "Public Relations",
  "Public Sector",
  "Publishing",
  "Quality Assurance",
  "Quantum Computing",
  "Railways",
  "Real Estate",
  "Recruitment",
  "Recycling",
  "Religious Services",
  "Renewable Energy",
  "Renewable Infrastructure",
  "Repair & Maintenance",
  "Research",
  "Research & Development (R&D)",
  "Restaurants",
  "Retail",
  "Retail Technology (RetailTech)",
  "Risk Management",
  "Robotics",
  "Rubber",
  "SaaS",
  "Schools",
  "Security Services",
  "Self-Help Groups (SHGs)",
  "Semiconductors",
  "SEO Services",
  "Shared Mobility",
  "Shipping",
  "Smart Agriculture",
  "Smart Cities",
  "Smart Home",
  "Smart Manufacturing",
  "Social Media Management",
  "Software Development",
  "Solar Energy",
  "Space Technology",
  "Sports",
  "Staffing",
  "Startups",
  "Steel",
  "Stock Broking",
  "Subscription Services",
  "Supply Chain",
  "Survey Services",
  "Tax Consulting",
  "Telecommunications",
  "Telecommunications Infrastructure",
  "Telemedicine",
  "Textile",
  "Tourism",
  "Trade Associations",
  "Training & Development",
  "Translation Services",
  "Transportation",
  "Travel & Tourism",
  "Utilities",
  "UX/UI Design",
  "Venture Capital",
  "Veterinary",
  "Virtual Assistance",
  "Warehousing",
  "Waste Management",
  "Water Treatment",
  "Web3",
  "Wedding Services",
  "Wholesale",
  "Wind Energy",
  "Wood Products",
];
