apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myworkspace-backend-pdb
  namespace: myworkspace
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: myworkspace-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: myworkspace-frontend-pdb
  namespace: myworkspace
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: myworkspace-frontend
